### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by simonschmoll** [simonschmoll/strengdurance#1]
Backend:

- [ ] Change all testing to mocking with jest
- [ ] Add Authentication layer
- [ ] Pipeline with travis-ci

Frontend:
Vue + CSS framework
- [ ] Basic functionality
  - [ ] Create new exercises (strength and endurance)
  - [ ] Create new workout (strength and endurance)
  - [ ] Display old workouts (strength and endurance)
